### ISSUE TITLE
Lab2 - GitPod - CQLSH execution error

### ISSUE THREAD

**Issue by ducmle** [datastaxdevs/workshop-swinburne#1]
@clun 

In Lab2, the command to execute the cqlsh throws an error about the Python module `six.moves` being not found. 

The error occurs on GitPod. However, running the same command on a local installation of `astra-cli` works ok. 

Do you know what's wrong?

- Command: 
```
astra db cqlsh workshops
```

- Error: 
```
gitpod /workspace/workshop-swinburne (main) $ astra db cqlsh workshops -k sensor_data
[INFO]  Downloading Cqlshell, please wait...
[INFO]  Installing  archive, please wait...
[INFO]  Cqlsh is starting, please wait for connection establishment...
Traceback (most recent call last):
  File "/home/gitpod/.astra/cqlsh-astra/bin/dsecqlsh.py", line 95, in <module>
    import cqlsh  # nopep8
    ^^^^^^^^^^^^
  File "/home/gitpod/.astra/cqlsh-astra/bin/cqlsh.py", line 153, in <module>
    from six.moves import configparser, input
ModuleNotFoundError: No module named 'six.moves'
```

**Comment by clun** [comment]
Seeing the issue only now. It is related to the version of python in use. I guess the Gitpod is using something too new for cqlsh like python 3.12. A solution would be to reinstall previous version of python
